# Site
repository: berkaygkv/resume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Berkay Gokova
title: Data Scientist
email: berkaygokova@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: upwork.com/freelancers/~01b59d4798b680689d
# website_title: Upwork

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: berkaygkv
github_username:  berkaygkv
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: berkaygkv
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Upwork
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: https://www.upwork.com/freelancers/~01b59d4798b680689d
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/linkedin profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a junior data scientist who has a huge interest in integrating programming skills into machine learning problems using <mark>Python</mark> and Python-based frameworks like 
  <mark>Pandas</mark>, <mark>Tensorflow</mark> and more. I love implementing Abstraction to my work when I code.
  
  
  I'm also interested in MLOps/Engineering stuff, trying to get a broader sense of how to implement technologies like Docker, Kubernetes, Airflow to ML projects. I have 1 year 
  experience in freelancing through [Upwork](https://www.upwork.com/freelancers/~01b59d4798b680689d) doing various kinds of
  jobs including Automation, Web Scraping, I have been working as a full-time data scientist for about a year now. I've got an MSc. in Cognitive Psychology. 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: LSTM Autoencoder
        link: https://nbviewer.org/github/berkaygkv/LSTM_Autoencoder/blob/master/anomaly_detection_nb.ipynb
        link_text: Nbviewer notebook
        additional_links:
          - title:  GitHub Link
            icon: fab fa-github
            url: https://github.com/berkaygkv/LSTM_Autoencoder 
        quote: >
          LSTM Autoencoder Neural Network to detect changepoints in Bitcoin prices
        description: | # this will include new lines to allow paragraphs
          - The model is built in Python using Tensorflow/Keras backend, 
          - I have assembled LSTM network into an Autoencoder architecture with customizable layer parameters,
          - The data is being smoothed by using Kalman Filter in the preprocessing phase to make the model more sensitive to trend changes,
          - All of the required operations for preprocessing, training and prediction can be handled simply by creating a Keras inherited Python instance. 
  - title: Experience
    layout: list
    content:
      - layout: top-left
        title: Vestel Trade Co.
        sub_title: Data Scientist
        caption: 2021 April - Present
      - layout: top-left
        title: Freelancer in Upwork
        sub_title: Python Programmer / Data Analyst
        caption: 2020 February - 2021 April
        link: https://bit.ly/2TmVWfc
      - layout: left
        title: Mentalift Consultancy
        sub_title: Data Analyst
        caption: 2017 September - 2018 February
        # quote: >
        #   Short description of the company (optional)
        # description: | # this will include new lines to allow paragraphs
        #   Description of role
  - title: Education
    layout: list
    content:
      - layout: top-right
        title:  Keele University
        sub_title: MSc. in Cognitive Psychology
        caption: 2018 - 2019
      - layout: top-right
        title:  Sabanci University
        sub_title: BA in Psychology
        caption: 2012 - 2017
        # quote: >
        #   Short institution or course description (optional)
        # description: | # this will include new lines to allow paragraphs
        #   Description of qualification
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
        * **Programming Languages:** Python, SQL
        * **Data Manipulation:** Pandas, Numpy
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
